version: '3'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: [ 'postgres', '-cshared_preload_libraries=pg_stat_statements' ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mybatis-test
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
